service: sls-slackciver

provider:
  profile: serverless
  runtime: nodejs6.10
  stage: prod
  name: aws
  timeout: 300
  environment:
      SLACK_API_TOKEN: 'your token goes here'

functions:
  sendToSlack:
    handler: handler.sendToSlack
    events:
      - http:
          path: channel/{channelName}/{topic}
          method: any
package:
  exclude:
    - test/**
